title: Welcome to my portfolio!
theme: jekyll-theme-cayman

# Cody DeGandi
<dl>
  <dt>Welcome to my page</dt>
  <dd>It is still a work in progress, just something to practice Markdown with!</dd>


[![IMAGE](http://img.youtube.com/vi/r1_8rRDHtQ8/0.jpg)](http://www.youtube.com/watch?v=r1_8rRDHtQ8)

  
