title: Welcome to my portfolio!
theme: jekyll-theme-cayman

# Cody DeGandi
## Welcome to my page</dt>
### It is still a work in progress, just something to practice Markdown with!</dd>
  ![Image of Me](https://github.com/degandi/markdown-portfolio/blob/add-images-links/_includes/Photo%20on%205-2-19%20at%203.47%20PM.jpg)



  [![IMAGE](http://img.youtube.com/vi/r1_8rRDHtQ8/0.jpg)](http://www.youtube.com/watch?v=r1_8rRDHtQ8)

  
